# Generated by Django 3.2.15 on 2022-08-25 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20220815_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateField(null=True, verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='deaprt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='所属部门'),
        ),
    ]
